var data = [{
  name: '商品',
  index: 1,
  icon: 'icon-xitongguanli',
  children: [{
    name: '一级子菜单1',
    index: 2,
    icon: 'icon-xitongguanli'
  }, {
    name: '一级子菜单2',
    index: 2,
    icon: 'icon-xitongguanli'
  }, {
    name: '一级子菜单3',
    index: 2,
    icon: 'icon-xitongguanli',
    children: [{
      name: '二级子菜单1',
      index: 3,
      icon: 'icon-xitongguanli'
    }, {
      name: '二级子菜单2',
      index: 3,
      icon: 'icon-xitongguanli'
    }, {
      name: '二级子菜单3',
      index: 3,
      icon: 'icon-xitongguanli',
      children: [{
        name: '管理页面',
        index: 4,
        icon: 'icon-xitongguanli',
        link: '/product/',
        isShow:false
      }, {
        name: '用户页面',
        index: 4,
        icon: 'icon-xitongguanli',
        link: '/product2/',
        isShow:false
      }, ]
    }, ]
  }]
}, {
  name: '订单',
  index: 1,
  icon: 'icon-dingjia',
  children: [{
    name: '一级子菜单1',
    index: 2,
    icon: 'icon-dingjia'
  }, {
    name: '一级子菜单2',
    index: 2,
    icon: 'icon-dingjia'
  }, {
    name: '一级子菜单3',
    index: 2,
    icon: 'icon-dingjia',
    children: [{
      name: '二级子菜单1',
      index: 3,
      icon: 'icon-dingjia'
    }, {
      name: '二级子菜单2',
      index: 3,
      icon: 'icon-dingjia'
    }, {
      name: '二级子菜单3',
      index: 3,
      icon: 'icon-dingjia',
      children: [{
        name: '三级子菜单1',
        index: 4,
        icon: 'icon-dingjia',
        link: '/order'
      }, {
        name: '三级子菜单2',
        index: 4,
        icon: 'icon-dingjia',
        link: '/order2'
      }, ]
    }, ]
  }]
}, {
  name: '内容',
  index: 1,
  icon: 'icon-shenqingtuikuan',
  children: [{
    name: '一级子菜单1',
    index: 2,
    icon: 'icon-shenqingtuikuan'
  }, {
    name: '一级子菜单2',
    index: 2,
    icon: 'icon-shenqingtuikuan'
  }, {
    name: '一级子菜单3',
    index: 2,
    icon: 'icon-shenqingtuikuan',
    children: [{
      name: '二级子菜单1',
      index: 3,
      icon: 'icon-shenqingtuikuan'
    }, {
      name: '二级子菜单2',
      index: 3,
      icon: 'icon-shenqingtuikuan'
    }, {
      name: '二级子菜单3',
      index: 3,
      icon: 'icon-shenqingtuikuan',
      children: [{
        name: '三级子菜单1',
        index: 4,
        icon: 'icon-shenqingtuikuan'
      }, {
        name: '三级子菜单2',
        index: 4,
        icon: 'icon-shenqingtuikuan'
      }, ]
    }, ]
  }]
}, {
  name: '内容',
  index: 1,
  icon: 'icon-zuzhiguanli',
  children: [{
    name: '一级子菜单1',
    index: 2,
    icon: 'icon-zuzhiguanli'
  }, {
    name: '一级子菜单2',
    index: 2,
    icon: 'icon-zuzhiguanli'
  }, {
    name: '一级子菜单3',
    index: 2,
    icon: 'icon-zuzhiguanli',
    children: [{
      name: '二级子菜单1',
      index: 3,
      icon: 'icon-zuzhiguanli'
    }, {
      name: '二级子菜单2',
      index: 3,
      icon: 'icon-zuzhiguanli'
    }, {
      name: '二级子菜单3',
      index: 3,
      icon: 'icon-zuzhiguanli',
      children: [{
        name: '三级子菜单1',
        index: 4,
        icon: 'icon-zuzhiguanli'
      }, {
        name: '三级子菜单2',
        index: 4,
        icon: 'icon-zuzhiguanli'
      }, ]
    }, ]
  }]
}]

